# .github/workflows/chromatic.yml

# Workflow name
name: 'Chromatic'

# Event for the workflow
on: push

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
        # 👇 Adds Chromatic as a step in the workflow
      - name: Publish Galaxy to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          buildScriptName: build-storybook-galaxy
          projectToken: ${{ secrets.CHROMATIC_GALAXY}}
          debug: true
        env:
          LOG_LEVEL: 'error'
      - name: Publish Starburst to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          buildScriptName: build-storybook-starburst
          projectToken: ${{ secrets.CHROMATIC_STARBURST}}
          debug: true
        env:
          LOG_LEVEL: 'error'
      - name: Publish Supernova to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          buildScriptName: build-storybook-supernova
          projectToken: ${{ secrets.CHROMATIC_SUPERNOVA}}
          debug: true
        env:
          LOG_LEVEL: 'error'
