# Workflow name
name: 'Chromatic - Supernova'

# Event for the workflow
on: push

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
        # 👇 Adds Chromatic as a step in the workflow
      - name: Publish Supernova to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          buildScriptName: build-storybook-supernova
          projectToken: ${{ secrets.CHROMATIC_SUPERNOVA}}
      - name: Archive Diagnostic Info
        uses: actions/upload-artifact@v3
        with:
          name: Chromatic Diagnostics
          path: chromatic-diagnostics.json
