# .github/workflows/chromatic.yml

# Workflow name
name: 'Chromatic'

# Event for the workflow
on: push

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - project: supernova
            buildScriptName: build-storybook-supernova
            chromaticSecretKey: CHROMATIC_SUPERNOVA
          - project: galaxy
            buildScriptName: build-storybook-galaxy
            chromaticSecretKey: CHROMATIC_GALAXY
          - project: starburst
            buildScriptName: build-storybook-starburst
            chromaticSecretKey: CHROMATIC_STARBURST
          - project: milky_way
            buildScriptName: build-storybook-milky-way
            chromaticSecretKey: CHROMATIC_MILKY_WAY
          - project: pluto
            buildScriptName: build-storybook-pluto
            chromaticSecretKey: CHROMATIC_PLUTO
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
        # 👇 Adds Chromatic as a step in the workflow
      - name: Publish ${{ matrix.project }} to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          buildScriptName: ${{ matrix.buildScriptName }}
          projectToken: ${{ secrets[matrix.chromaticSecretKey] }}
          onlyChanged: true
          debug: true
