# .github/workflows/chromatic.yml

# Workflow name
name: 'Chromatic'

# Event for the workflow
on: [push, workflow_dispatch]

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
      - name: Publish Galaxy to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          buildScriptName: build-storybook-galaxy
          projectToken: ${{ secrets.CHROMATIC_GALAXY}}
      - name: Archive Diagnostic Info
        uses: actions/upload-artifact@v3
        with:
          name: Chromatic Diagnostics
          path: chromatic-diagnostics.json
      - name: Publish Milky Way to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          buildScriptName: build-storybook-milky-way
          projectToken: ${{ secrets.CHROMATIC_MILKY_WAY}}
          diagnostics: true
        env:
          LOG_LEVEL: debug
